export interface LeaderboardEntry {
  apiPricing?: string;
  creator: string;
  elo: number;
  isCurrent?: boolean;
  model: string;
  rank: number;
  routableModelId?: string;
}

export interface LeaderboardSnapshot {
  capturedAt: string;
  entries: LeaderboardEntry[];
  source: string;
}

export const IMAGE_TEXT_TO_IMAGE_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  source: "https://artificialanalysis.ai/image/leaderboard/text-to-image",
  entries: [
    {
      rank: 1,
      creator: "OpenAI",
      model: "GPT Image 2 (high)",
      elo: 1337,
      apiPricing: "$211/1k images",
      isCurrent: true,
      routableModelId: "gpt2",
    },
    {
      rank: 2,
      creator: "OpenAI",
      model: "GPT Image 1.5 (high)",
      elo: 1268,
      apiPricing: "$133/1k images",
      isCurrent: true,
      routableModelId: "gpt",
    },
    {
      rank: 3,
      creator: "Google",
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      elo: 1263,
      apiPricing: "$67/1k images",
      isCurrent: true,
      routableModelId: "banana2",
    },
    {
      rank: 4,
      creator: "Sourceful",
      model: "Riverflow 2.0",
      elo: 1256,
      apiPricing: "$150/1k images",
      isCurrent: true,
    },
    {
      rank: 5,
      creator: "Google",
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      elo: 1220,
      apiPricing: "$134/1k images",
      isCurrent: true,
      routableModelId: "banana",
    },
    {
      rank: 6,
      creator: "ByteDance Seed",
      model: "Seedream 4.0",
      elo: 1198,
      apiPricing: "$30/1k images",
      isCurrent: true,
      routableModelId: "seedream4",
    },
    {
      rank: 7,
      creator: "Microsoft",
      model: "MAI-Image-2",
      elo: 1198,
      apiPricing: "$50/1k images",
      isCurrent: true,
    },
    {
      rank: 8,
      creator: "Black Forest Labs",
      model: "FLUX.2 [max]",
      elo: 1197,
      apiPricing: "$70/1k images",
      isCurrent: true,
      routableModelId: "flux2-max",
    },
    {
      rank: 9,
      creator: "Peanut",
      model: "Peanut (Open Weights Coming Soon)",
      elo: 1187,
      apiPricing: "Unavailable",
      isCurrent: true,
    },
    {
      rank: 10,
      creator: "Black Forest Labs",
      model: "FLUX.2 [pro]",
      elo: 1186,
      apiPricing: "$30/1k images",
      isCurrent: true,
      routableModelId: "flux2-pro",
    },
    {
      rank: 11,
      creator: "Google",
      model: "Imagen 4 Ultra Preview 0606",
      elo: 1184,
      apiPricing: "$60/1k images",
      isCurrent: false,
    },
    {
      rank: 12,
      creator: "xAI",
      model: "grok-imagine-image",
      elo: 1182,
      apiPricing: "$20/1k images",
      isCurrent: true,
      routableModelId: "grok-image",
    },
    {
      rank: 13,
      creator: "Black Forest Labs",
      model: "FLUX.2 [flex]",
      elo: 1182,
      apiPricing: "$60/1k images",
      isCurrent: true,
      routableModelId: "flux2-flex",
    },
    {
      rank: 14,
      creator: "ImagineArt",
      model: "ImagineArt 2.0",
      elo: 1181,
      apiPricing: "$30/1k images",
      isCurrent: true,
    },
    {
      rank: 15,
      creator: "Google",
      model: "Imagen 4 Ultra",
      elo: 1171,
      apiPricing: "$60/1k images",
      isCurrent: true,
    },
    {
      rank: 16,
      creator: "Google",
      model: "Imagen 4 Preview 0606",
      elo: 1169,
      apiPricing: "$40/1k images",
      isCurrent: false,
    },
    {
      rank: 17,
      creator: "ByteDance Seed",
      model: "Seedream 4.5",
      elo: 1167,
      apiPricing: "$40/1k images",
      isCurrent: true,
      routableModelId: "seedream45",
    },
    {
      rank: 18,
      creator: "Fal",
      model: "FLUX.2 [dev] Turbo",
      elo: 1161,
      apiPricing: "$8/1k images",
      isCurrent: true,
    },
    {
      rank: 19,
      creator: "Black Forest Labs",
      model: "FLUX.2 [dev]",
      elo: 1160,
      apiPricing: "$12/1k images",
      isCurrent: true,
      routableModelId: "flux2-dev",
    },
    {
      rank: 20,
      creator: "Alibaba",
      model: "Qwen Image Max 2512",
      elo: 1158,
      apiPricing: "$20/1k images",
      isCurrent: true,
      routableModelId: "qwen",
    },
  ],
};

export const IMAGE_EDITING_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  source: "https://artificialanalysis.ai/image/leaderboard/editing",
  entries: [
    {
      rank: 1,
      creator: "Sourceful",
      model: "Riverflow 2.0",
      elo: 1286,
      apiPricing: "$150/1k images",
      isCurrent: true,
    },
    {
      rank: 2,
      creator: "OpenAI",
      model: "GPT Image 1.5 (high)",
      elo: 1262,
      apiPricing: "$133/1k images",
      isCurrent: true,
      routableModelId: "gpt",
    },
    {
      rank: 3,
      creator: "OpenAI",
      model: "GPT Image 2 (high)",
      elo: 1249,
      apiPricing: "$211/1k images",
      isCurrent: true,
      routableModelId: "gpt2",
    },
    {
      rank: 4,
      creator: "Google",
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      elo: 1241,
      apiPricing: "$134/1k images",
      isCurrent: true,
      routableModelId: "banana",
    },
    {
      rank: 5,
      creator: "Google",
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      elo: 1231,
      apiPricing: "$67/1k images",
      isCurrent: true,
      routableModelId: "banana2",
    },
    {
      rank: 6,
      creator: "Tencent",
      model: "HunyuanImage 3.0 Instruct (Fal)",
      elo: 1222,
      apiPricing: "$90/1k images",
      isCurrent: true,
    },
    {
      rank: 7,
      creator: "xAI",
      model: "grok-imagine-image",
      elo: 1213,
      apiPricing: "$20/1k images",
      isCurrent: true,
      routableModelId: "grok-image",
    },
    {
      rank: 8,
      creator: "xAI",
      model: "grok-imagine-image-pro",
      elo: 1212,
      apiPricing: "$70/1k images",
      isCurrent: true,
    },
    {
      rank: 9,
      creator: "KlingAI",
      model: "Kling Image 3.0 Omni",
      elo: 1207,
      apiPricing: "Unavailable",
      isCurrent: true,
    },
    {
      rank: 10,
      creator: "Black Forest Labs",
      model: "FLUX.2 [max]",
      elo: 1206,
      apiPricing: "$140/1k images",
      isCurrent: true,
      routableModelId: "flux2-max",
    },
    {
      rank: 11,
      creator: "Alibaba",
      model: "Wan 2.7 Pro",
      elo: 1200,
      apiPricing: "Unavailable",
      isCurrent: true,
    },
    {
      rank: 12,
      creator: "KlingAI",
      model: "Kling Image 3.0",
      elo: 1196,
      apiPricing: "$28/1k images",
      isCurrent: true,
    },
    {
      rank: 13,
      creator: "KlingAI",
      model: "Kling Image O1",
      elo: 1193,
      apiPricing: "$28/1k images",
      isCurrent: true,
    },
    {
      rank: 14,
      creator: "Alibaba",
      model: "Wan 2.6 Image",
      elo: 1188,
      apiPricing: "$30/1k images",
      isCurrent: true,
    },
    {
      rank: 15,
      creator: "Sourceful",
      model: "Riverflow 1",
      elo: 1184,
      apiPricing: "$66/1k images",
      isCurrent: true,
    },
    {
      rank: 16,
      creator: "ByteDance Seed",
      model: "Seedream 4.0",
      elo: 1184,
      apiPricing: "$30/1k images",
      isCurrent: true,
      routableModelId: "seedream4",
    },
    {
      rank: 17,
      creator: "ByteDance Seed",
      model: "Seedream 4.5",
      elo: 1184,
      apiPricing: "$40/1k images",
      isCurrent: true,
      routableModelId: "seedream45",
    },
    {
      rank: 18,
      creator: "Alibaba",
      model: "Wan 2.7",
      elo: 1181,
      apiPricing: "$26/1k images",
      isCurrent: true,
    },
    {
      rank: 19,
      creator: "Google",
      model: "Nano Banana (Gemini 2.5 Flash Image)",
      elo: 1173,
      apiPricing: "$39/1k images",
      isCurrent: true,
      routableModelId: "gemini",
    },
    {
      rank: 20,
      creator: "Reve",
      model: "Reve V1 (December)",
      elo: 1172,
      apiPricing: "$40/1k images",
      isCurrent: true,
    },
  ],
};

export const VIDEO_TEXT_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  source: "https://artificialanalysis.ai/video/leaderboard/text-to-video",
  entries: [
    {
      rank: 1,
      creator: "Alibaba-ATH",
      model: "HappyHorse-1.0",
      elo: 1354,
      apiPricing: "$14.40/min",
    },
    {
      rank: 2,
      creator: "ByteDance Seed",
      model: "Dreamina Seedance 2.0 720p",
      elo: 1273,
      apiPricing: "No API available",
    },
    {
      rank: 3,
      creator: "KlingAI",
      model: "Kling 3.0 1080p (Pro)",
      elo: 1249,
      apiPricing: "$13.44/min",
    },
    {
      rank: 4,
      creator: "KlingAI",
      model: "Kling 3.0 Omni 1080p (Pro)",
      elo: 1233,
      apiPricing: "$13.44/min",
    },
    {
      rank: 5,
      creator: "xAI",
      model: "grok-imagine-video",
      elo: 1233,
      apiPricing: "$4.20/min",
    },
    {
      rank: 6,
      creator: "Vidu",
      model: "Vidu Q3 Pro",
      elo: 1225,
      apiPricing: "$9.60/min",
    },
    {
      rank: 7,
      creator: "Video Rebirth",
      model: "Bach-1.0 Preview",
      elo: 1224,
      apiPricing: "$3.00/min",
    },
    {
      rank: 8,
      creator: "KlingAI",
      model: "Kling 3.0 Omni 720p (Standard)",
      elo: 1224,
      apiPricing: "$10.08/min",
    },
    {
      rank: 9,
      creator: "PixVerse",
      model: "PixVerse V6",
      elo: 1222,
      apiPricing: "$5.40/min",
    },
    {
      rank: 10,
      creator: "PixVerse",
      model: "PixVerse V5.6",
      elo: 1221,
      apiPricing: "$9.00/min",
    },
    {
      rank: 11,
      creator: "Runway",
      model: "Runway Gen-4.5",
      elo: 1220,
      apiPricing: "No API available",
    },
    {
      rank: 12,
      creator: "Google",
      model: "Veo 3",
      elo: 1218,
      apiPricing: "$12.00/min",
    },
    {
      rank: 13,
      creator: "KlingAI",
      model: "Kling 3.0 720p (Standard)",
      elo: 1215,
      apiPricing: "$10.08/min",
    },
    {
      rank: 14,
      creator: "Google",
      model: "Veo 3.1 Lite",
      elo: 1214,
      apiPricing: "$3.00/min",
    },
    {
      rank: 15,
      creator: "KlingAI",
      model: "Kling O1 Pro (January)",
      elo: 1209,
      apiPricing: "$10.08/min",
    },
  ],
};

export const VIDEO_IMAGE_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  source: "https://artificialanalysis.ai/video/leaderboard/image-to-video",
  entries: [
    {
      rank: 1,
      creator: "Alibaba-ATH",
      model: "HappyHorse-1.0",
      elo: 1395,
      apiPricing: "Coming soon",
    },
    {
      rank: 2,
      creator: "ByteDance Seed",
      model: "Dreamina Seedance 2.0 720p",
      elo: 1348,
      apiPricing: "No API available",
    },
    {
      rank: 3,
      creator: "xAI",
      model: "grok-imagine-video",
      elo: 1326,
      apiPricing: "$4.20/min",
    },
    {
      rank: 4,
      creator: "PixVerse",
      model: "PixVerse V6",
      elo: 1322,
      apiPricing: "$5.40/min",
    },
    {
      rank: 5,
      creator: "Vidu",
      model: "Vidu Q3 Pro",
      elo: 1287,
      apiPricing: "$9.60/min",
    },
    {
      rank: 6,
      creator: "KlingAI",
      model: "Kling 2.5 Turbo 1080p",
      elo: 1283,
      apiPricing: "$4.20/min",
    },
    {
      rank: 7,
      creator: "KlingAI",
      model: "Kling 3.0 1080p (Pro)",
      elo: 1280,
      apiPricing: "$13.44/min",
    },
    {
      rank: 8,
      creator: "PixVerse",
      model: "PixVerse V5.6",
      elo: 1279,
      apiPricing: "$9.00/min",
    },
    {
      rank: 9,
      creator: "KlingAI",
      model: "Kling 3.0 Omni 1080p (Pro)",
      elo: 1277,
      apiPricing: "$13.44/min",
    },
    {
      rank: 10,
      creator: "KlingAI",
      model: "Kling 2.6 Standard (January)",
      elo: 1271,
      apiPricing: "Coming soon",
    },
    {
      rank: 11,
      creator: "PixVerse",
      model: "PixVerse V5.5",
      elo: 1271,
      apiPricing: "$6.40/min",
    },
    {
      rank: 12,
      creator: "Google",
      model: "Veo 3.1 Fast",
      elo: 1268,
      apiPricing: "$6.00/min",
    },
    {
      rank: 13,
      creator: "Runway",
      model: "Runway Gen-4.5",
      elo: 1263,
      apiPricing: "No API available",
    },
    {
      rank: 14,
      creator: "KlingAI",
      model: "Kling 3.0 Omni 720p (Standard)",
      elo: 1263,
      apiPricing: "$10.08/min",
    },
    {
      rank: 15,
      creator: "KlingAI",
      model: "Kling 3.0 720p (Standard)",
      elo: 1263,
      apiPricing: "$10.08/min",
    },
  ],
};
