import type { ModelConfig } from "./types";

const AA_IMAGE_LEADERBOARD_SNAPSHOT = "2026-05-12";
const AA_IMAGE_SOURCES = [
  "https://artificialanalysis.ai/image/leaderboard/text-to-image",
  "https://artificialanalysis.ai/image/leaderboard/editing",
];
const FAL_PRICING_CHECKED_AT = "2026-05-12";
// July 2026 tier-1 additions (MOT-18): verified against fal model pages.
const FAL_PRICING_CHECKED_JUL_2026 = "2026-07-11";

export const MODELS: Record<string, ModelConfig> = {
  // ─── Generation Models ────────────────────────────────────────

  gpt2: {
    name: "GPT Image 2",
    endpoint: "openai/gpt-image-2",
    editEndpoint: "openai/gpt-image-2/image-to-image",
    type: "generation",
    pricing: "$0.211",
    pricePerImageUsd: 0.211,
    falPricing: {
      endpointId: "openai/gpt-image-2",
      unitPrice: 1,
      unit: "units",
      currency: "USD",
      estimatedCostPerImageUsd: 0.211,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Highest-ranked text-to-image quality and transparent PNGs",
      tiers: { quality: "frontier", speed: "very_slow", price: "ultra" },
      speed: {
        medianSeconds: 200.7,
        p95Seconds: 232.6,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 1, elo: 1337, winRate: 0.8, pricePer1k: 211 },
        editing: { rank: 3, elo: 1249, winRate: 0.66, pricePer1k: 211 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsMaskImage: true,
    supportsSyncMode: true,
    maxReferenceImages: 4,
    useQueue: true,
  },
  gpt: {
    name: "GPT Image 1.5",
    endpoint: "fal-ai/gpt-image-1.5",
    editEndpoint: "fal-ai/gpt-image-1.5/edit",
    type: "generation",
    pricing: "$0.133",
    pricePerImageUsd: 0.133,
    falPricing: {
      endpointId: "fal-ai/gpt-image-1.5",
      unitPrice: 1,
      unit: "units",
      currency: "USD",
      estimatedCostPerImageUsd: 0.133,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Best OpenAI edit quality with transparent PNG support",
      tiers: { quality: "frontier", speed: "slow", price: "ultra" },
      speed: {
        medianSeconds: 34.6,
        p95Seconds: 38.3,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 2, elo: 1268, winRate: 0.73, pricePer1k: 133 },
        editing: { rank: 2, elo: 1262, winRate: 0.69, pricePer1k: 133 },
      },
    },
    sizeMode: "gpt_size",
    supportsAspect: false,
    supportsBackground: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsMaskImage: true,
    supportsSyncMode: true,
    maxReferenceImages: 4,
  },
  banana2: {
    name: "Nano Banana 2",
    endpoint: "fal-ai/nano-banana-2",
    editEndpoint: "fal-ai/nano-banana-2/edit",
    type: "generation",
    pricing: "$0.08",
    pricePerImageUsd: 0.08,
    falPricing: {
      endpointId: "fal-ai/nano-banana-2",
      unitPrice: 0.08,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.08,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Best balance of quality, edit support, web search, and cost",
      tiers: { quality: "frontier", speed: "unknown", price: "premium" },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 3, elo: 1263, winRate: 0.71, pricePer1k: 67 },
        editing: { rank: 5, elo: 1231, winRate: 0.63, pricePer1k: 67 },
      },
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsWebSearch: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsSyncMode: true,
    supportsThinkingLevel: true,
    maxReferenceImages: 4,
  },
  banana: {
    name: "Nano Banana Pro",
    endpoint: "fal-ai/nano-banana-pro",
    editEndpoint: "fal-ai/nano-banana-pro/edit",
    type: "generation",
    pricing: "$0.15",
    pricePerImageUsd: 0.15,
    falPricing: {
      endpointId: "fal-ai/nano-banana-pro",
      unitPrice: 0.15,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Premium Gemini image generation and multi-reference edits",
      tiers: { quality: "frontier", speed: "balanced", price: "ultra" },
      speed: {
        medianSeconds: 19.2,
        p95Seconds: 30.3,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 5, elo: 1220, winRate: 0.66, pricePer1k: 134 },
        editing: { rank: 4, elo: 1241, winRate: 0.65, pricePer1k: 134 },
      },
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsWebSearch: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsSyncMode: true,
    maxReferenceImages: 14,
  },
  gemini: {
    name: "Gemini 2.5 Flash",
    endpoint: "fal-ai/gemini-25-flash-image",
    editEndpoint: "fal-ai/gemini-25-flash-image/edit",
    type: "generation",
    pricing: "$0.04",
    pricePerImageUsd: 0.0398,
    falPricing: {
      endpointId: "fal-ai/gemini-25-flash-image",
      unitPrice: 0.0398,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.0398,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 4,
  },
  gemini3: {
    name: "Gemini 3 Pro",
    endpoint: "fal-ai/gemini-3-pro-image-preview",
    editEndpoint: "fal-ai/gemini-3-pro-image-preview/edit",
    type: "generation",
    pricing: "$0.15",
    pricePerImageUsd: 0.15,
    falPricing: {
      endpointId: "fal-ai/gemini-3-pro-image-preview",
      unitPrice: 0.15,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsWebSearch: true,
    supportsSyncMode: true,
    maxReferenceImages: 4,
  },
  seedream4: {
    name: "Seedream 4.0",
    endpoint: "fal-ai/bytedance/seedream/v4/text-to-image",
    editEndpoint: "fal-ai/bytedance/seedream/v4/edit",
    type: "generation",
    pricing: "$0.03",
    pricePerImageUsd: 0.03,
    falPricing: {
      endpointId: "fal-ai/bytedance/seedream/v4/text-to-image",
      unitPrice: 0.03,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "High-ranked budget generation and large multi-reference edits",
      tiers: { quality: "best", speed: "balanced", price: "budget" },
      speed: {
        medianSeconds: 14.3,
        p95Seconds: 21,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 6, elo: 1198, winRate: 0.59, pricePer1k: 30 },
        editing: { rank: 16, elo: 1184, winRate: 0.61, pricePer1k: 30 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  seedream45: {
    name: "Seedream 4.5",
    endpoint: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    editEndpoint: "fal-ai/bytedance/seedream/v4.5/edit",
    type: "generation",
    pricing: "$0.04",
    pricePerImageUsd: 0.04,
    falPricing: {
      endpointId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
      unitPrice: 0.04,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Cheap current Seedream model with good animation/art scores",
      tiers: { quality: "better", speed: "balanced", price: "standard" },
      speed: {
        medianSeconds: 18.2,
        p95Seconds: 43.3,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 17, elo: 1167, winRate: 0.63, pricePer1k: 40 },
        editing: { rank: 17, elo: 1184, winRate: 0.58, pricePer1k: 40 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  seedream5: {
    name: "Seedream 5.0 Pro",
    endpoint: "bytedance/seedream/v5/pro/text-to-image",
    editEndpoint: "bytedance/seedream/v5/pro/edit",
    type: "generation",
    // fal tiers Seedream v5 Pro by output size: $0.0675 up to 1536², $0.135 up to 2048².
    pricing: "$0.0675 (≤1536²) / $0.135 (≤2048²)",
    pricePerImageUsd: 0.0675,
    falPricing: {
      endpointId: "bytedance/seedream/v5/pro/text-to-image",
      unitPrice: 0.0675,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.0675,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "seedream5-lite": {
    name: "Seedream 5.0 Lite",
    endpoint: "fal-ai/bytedance/seedream/v5/lite/text-to-image",
    editEndpoint: "fal-ai/bytedance/seedream/v5/lite/edit",
    type: "generation",
    // Flat price regardless of resolution; native up to Auto 3K (~9.4MP).
    pricing: "$0.035",
    pricePerImageUsd: 0.035,
    falPricing: {
      endpointId: "fal-ai/bytedance/seedream/v5/lite/text-to-image",
      unitPrice: 0.035,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.035,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-max": {
    name: "FLUX.2 Max",
    endpoint: "fal-ai/flux-2-max",
    editEndpoint: "fal-ai/flux-2-max/edit",
    type: "generation",
    pricing: "$0.07/MP",
    pricePerImageUsd: 0.07,
    falPricing: {
      endpointId: "fal-ai/flux-2-max",
      unitPrice: 0.07,
      unit: "megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.07,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Best FLUX quality and high-end editing",
      tiers: { quality: "best", speed: "slow", price: "premium" },
      speed: {
        medianSeconds: 31.6,
        p95Seconds: 41,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 8, elo: 1197, winRate: 0.67, pricePer1k: 70 },
        editing: { rank: 10, elo: 1206, winRate: 0.6, pricePer1k: 140 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-pro": {
    name: "FLUX.2 Pro",
    endpoint: "fal-ai/flux-2-pro",
    editEndpoint: "fal-ai/flux-2-pro/edit",
    type: "generation",
    pricing: "$0.03/MP",
    pricePerImageUsd: 0.03,
    falPricing: {
      endpointId: "fal-ai/flux-2-pro",
      unitPrice: 0.03,
      unit: "processed megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Production FLUX quality at a low per-megapixel price",
      tiers: { quality: "best", speed: "balanced", price: "budget" },
      speed: {
        medianSeconds: 16.1,
        p95Seconds: 23.9,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 10, elo: 1186, winRate: 0.62, pricePer1k: 30 },
        editing: { rank: 21, elo: 1170, pricePer1k: 30 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-flex": {
    name: "FLUX.2 Flex",
    endpoint: "fal-ai/flux-2-flex",
    editEndpoint: "fal-ai/flux-2-flex/edit",
    type: "generation",
    pricing: "$0.05/MP",
    pricePerImageUsd: 0.05,
    falPricing: {
      endpointId: "fal-ai/flux-2-flex",
      unitPrice: 0.05,
      unit: "processed megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.05,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "FLUX quality with guidance and step controls",
      tiers: { quality: "best", speed: "balanced", price: "standard" },
      speed: {
        medianSeconds: 15.3,
        p95Seconds: 22.2,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 13, elo: 1182, winRate: 0.61, pricePer1k: 60 },
        editing: { rank: 22, elo: 1161, pricePer1k: 60 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportedOutputFormats: ["jpeg", "png"],
    supportsSafetyTolerance: true,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-dev": {
    name: "FLUX.2 [dev]",
    endpoint: "fal-ai/flux-2",
    editEndpoint: "fal-ai/flux-2/edit",
    type: "generation",
    pricing: "$0.00167/sec",
    pricePerImageUsd: 0.012,
    falPricing: {
      endpointId: "fal-ai/flux-2",
      unitPrice: 0.00167,
      unit: "compute seconds",
      currency: "USD",
      estimatedCostPerImageUsd: 0.012,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Open FLUX.2 quality with low average cost",
      tiers: { quality: "better", speed: "fast", price: "variable" },
      speed: {
        medianSeconds: 4.6,
        p95Seconds: 69.6,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 19, elo: 1160, winRate: 0.57, pricePer1k: 12 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyTolerance: true,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-turbo": {
    name: "FLUX.2 Turbo",
    endpoint: "fal-ai/flux-2/turbo",
    type: "generation",
    pricing: "$0.008/MP",
    pricePerImageUsd: 0.008,
    falPricing: {
      endpointId: "fal-ai/flux-2/turbo",
      unitPrice: 0.008,
      unit: "megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.008,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsGuidanceScale: true,
    supportsSyncMode: true,
  },
  flux: {
    name: "FLUX Pro Ultra",
    endpoint: "fal-ai/flux-pro/v1.1-ultra",
    type: "generation",
    pricing: "$0.06",
    pricePerImageUsd: 0.06,
    falPricing: {
      endpointId: "fal-ai/flux-pro/v1.1-ultra",
      unitPrice: 0.06,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.06,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsRaw: true,
    supportsEnhancePrompt: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsImagePromptStrength: true,
    supportsSyncMode: true,
    maxReferenceImages: 1,
  },
  "flux-fast": {
    name: "FLUX Schnell",
    endpoint: "fal-ai/flux/schnell",
    type: "generation",
    pricing: "$0.003",
    pricePerImageUsd: 0.003,
    falPricing: {
      endpointId: "fal-ai/flux/schnell",
      unitPrice: 0.003,
      unit: "megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.003,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsSeed: true,
    supportsSyncMode: true,
  },
  recraft: {
    name: "Recraft V3",
    endpoint: "fal-ai/recraft-v3",
    type: "generation",
    pricing: "$0.04",
    pricePerImageUsd: 0.04,
    falPricing: {
      endpointId: "fal-ai/recraft-v3",
      unitPrice: 0.04,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsStyle: true,
    supportsSyncMode: true,
  },
  recraft4: {
    name: "Recraft V4",
    endpoint: "fal-ai/recraft/v4/text-to-image",
    type: "generation",
    pricing: "$0.04",
    pricePerImageUsd: 0.04,
    falPricing: {
      endpointId: "fal-ai/recraft/v4/text-to-image",
      unitPrice: 0.04,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsStyle: true,
    supportsSyncMode: true,
  },
  ideogram: {
    name: "Ideogram V3",
    endpoint: "fal-ai/ideogram/v3",
    type: "generation",
    pricing: "$0.03",
    pricePerImageUsd: 0.03,
    falPricing: {
      endpointId: "fal-ai/ideogram/v3",
      unitPrice: 0.03,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsExpandPrompt: true,
    supportsNegativePrompt: true,
    supportsRenderingSpeed: true,
    supportsSeed: true,
    supportsStyle: true,
    supportsSyncMode: true,
  },
  ideogram4: {
    name: "Ideogram V4",
    endpoint: "ideogram/v4",
    type: "generation",
    // fal bills v4 per output megapixel by rendering speed: TURBO $0.03, BALANCED
    // $0.06, QUALITY $0.10 (plus a flat $0.03 when prompt expansion is used).
    // Headline uses the TURBO 1MP rate, matching how ideogram v3 is modeled.
    pricing: "$0.03",
    pricePerImageUsd: 0.03,
    falPricing: {
      endpointId: "ideogram/v4",
      unitPrice: 0.03,
      unit: "megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsSeed: true,
    supportsOutputFormat: true,
    supportedOutputFormats: ["jpeg", "png"],
    supportsSafetyChecker: true,
    supportsSyncMode: true,
  },
  "grok-image": {
    name: "Grok Imagine Image",
    endpoint: "xai/grok-imagine-image",
    editEndpoint: "xai/grok-imagine-image/edit",
    type: "generation",
    pricing: "$0.02",
    pricePerImageUsd: 0.02,
    falPricing: {
      endpointId: "xai/grok-imagine-image",
      unitPrice: 0.02,
      unit: "images",
      currency: "USD",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Very fast, cheap generation and edits",
      tiers: { quality: "best", speed: "fast", price: "budget" },
      speed: {
        medianSeconds: 5.1,
        p95Seconds: 6.5,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 12, elo: 1182, winRate: 0.6, pricePer1k: 20 },
        editing: { rank: 7, elo: 1213, winRate: 0.6, pricePer1k: 20 },
      },
    },
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsResolution: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSyncMode: true,
    maxReferenceImages: 4,
  },
  qwen: {
    name: "Qwen Image",
    endpoint: "fal-ai/qwen-image",
    type: "generation",
    pricing: "$0.02/MP",
    pricePerImageUsd: 0.02,
    falPricing: {
      endpointId: "fal-ai/qwen-image",
      unitPrice: 0.02,
      unit: "megapixels",
      currency: "USD",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      checkedAt: FAL_PRICING_CHECKED_AT,
    },
    benchmark: {
      useCase: "Low-cost open-weight text and design generation",
      tiers: { quality: "better", speed: "slow", price: "budget" },
      speed: {
        medianSeconds: 23.3,
        p95Seconds: 491,
        source: "artificial-analysis-models",
      },
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { rank: 20, elo: 1158, winRate: 0.6, pricePer1k: 20 },
      },
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsSeed: true,
    supportsSyncMode: true,
  },

  // ─── Video Models ─────────────────────────────────────────────

  kling: {
    name: "Kling v3 Pro",
    endpoint: "fal-ai/kling-video/v3/pro/image-to-video",
    type: "video",
    pricing: "$0.11/sec",
    sizeMode: "none",
    supportsAspect: false,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
  },

  // ─── Utility Models ───────────────────────────────────────────

  clarity: {
    name: "Clarity Upscaler",
    endpoint: "fal-ai/clarity-upscaler",
    type: "utility",
    pricing: "$0.03/MP",
    supportsAspect: false,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
  },
  crystal: {
    name: "Crystal Upscaler",
    endpoint: "clarityai/crystal-upscaler",
    type: "utility",
    pricing: "$0.02",
    supportsAspect: false,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
  },
  rmbg: {
    name: "BiRefNet (Background Removal)",
    endpoint: "fal-ai/birefnet",
    type: "utility",
    pricing: "$0.02",
    supportsAspect: false,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
  },
  bria: {
    name: "Bria RMBG 2.0",
    endpoint: "fal-ai/bria/background/remove",
    type: "utility",
    pricing: "$0.02",
    supportsAspect: false,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: false,
  },
};

export const GENERATION_MODELS = [
  "gpt2",
  "gpt",
  "banana2",
  "banana",
  "gemini",
  "gemini3",
  "seedream4",
  "seedream45",
  "seedream5",
  "seedream5-lite",
  "flux2-max",
  "flux2-pro",
  "flux2-flex",
  "flux2-dev",
  "flux2-turbo",
  "flux",
  "flux-fast",
  "recraft",
  "recraft4",
  "ideogram",
  "ideogram4",
  "grok-image",
  "qwen",
] as const;

/** Models whose fal endpoints support image editing (vary/edit flows). */
export const EDIT_CAPABLE_MODELS = GENERATION_MODELS.filter(
  (id) => MODELS[id]?.supportsEdit,
);

export const UTILITY_MODELS = ["clarity", "crystal", "rmbg", "bria"] as const;

export const VIDEO_MODELS = ["kling"] as const;

export type GenerationModelName = (typeof GENERATION_MODELS)[number];

/** Recraft v3 style presets. Pass as the `style` field in GenerateOptions. */
export const RECRAFT_STYLES = [
  // Realistic
  "realistic_image",
  "realistic_image/b_and_w",
  "realistic_image/enterprise",
  "realistic_image/hard_flash",
  "realistic_image/hdr",
  "realistic_image/motion_blur",
  "realistic_image/natural_light",
  "realistic_image/studio_portrait",
  "realistic_image/long_exposure",
  // Digital illustration
  "digital_illustration",
  "digital_illustration/2d_art_poster",
  "digital_illustration/2d_art_poster_2",
  "digital_illustration/engraving_color",
  "digital_illustration/grain",
  "digital_illustration/hand_drawn",
  "digital_illustration/hand_drawn_outline",
  "digital_illustration/handmade_3d",
  "digital_illustration/infantile_sketch",
  "digital_illustration/pixel_art",
  "digital_illustration/psychedelic",
  "digital_illustration/seamless",
  "digital_illustration/voxel",
  "digital_illustration/watercolor",
  // Vector illustration
  "vector_illustration",
  "vector_illustration/cartoon",
  "vector_illustration/doodle_line_art",
  "vector_illustration/engraving",
  "vector_illustration/flat_2",
  "vector_illustration/kawaii",
  "vector_illustration/line_art",
  "vector_illustration/line_circuit",
  "vector_illustration/linocut",
  "vector_illustration/zentangle",
] as const;

/** Ideogram v3 top-level style categories. Pass as the `style` field in GenerateOptions. */
export const IDEOGRAM_STYLES = [
  "AUTO",
  "GENERAL",
  "REALISTIC",
  "DESIGN",
] as const;
